spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    # contexts: dev  # 可选，指定执行上下文
    drop-first: false  # 警告：设置为 true 会先删除数据库，谨慎使用
    parameters:
      enableEscaping: true
  profiles:
    active: dev
  data:
    redis:
      host: ${database.redisHost}
      port: 6379
server:
  servlet:
    context-path: /api
netty:
  port: 8081
